/**
 * app module
 */
const SET_APP_CURRENCY = 'SET_APP_CURRENCY'
const GEN_PAY = 'GEN_PAY'
const SET_LOADING = 'SET_LOADING'
const SET_SUBMIT_LOADING = 'SET_SUBMIT_LOADING'
const SHOW_ALERT = 'SHOW_ALERT'
const SHOW_CONFIRM = 'SHOW_CONFIRM'
const HIDE_CONFIRM = 'HIDE_CONFIRM'
/**
 * user module
 */
const SET_DEFAULT_ADDRESS = 'SET_DEFAULT_ADDRESS'
const SET_MODIFY_ADDRESS = 'SET_MODIFY_ADDRESS'
const SET_SELECT_ADDRESS = 'SET_SELECT_ADDRESS'
const SET_PAY_ORDER = 'SET_PAY_ORDER'

/**
 * cart module
 */
const ADD_TO_CART = 'ADD_TO_CART'
const RECEIVE_SHOPPING_INFO = 'RECEIVE_SHOPPING_INFO'
const GET_CART_LIST = 'GET_CART_LIST'
const INIT_SHOPPING_DISPLAY = 'INIT_SHOPPING_DISPLAY'
const UPDATE_SHOPPING_DISPLAY = 'UPDATE_SHOPPING_DISPLAY'
const SELECT_ALL_SHOPPING = 'SELECT_ALL_SHOPPING'
const SELECT_SHOP_SHOPPING = 'SELECT_SHOP_SHOPPING'
const SELECT_SHOPPING = 'SELECT_SHOPPING'
const INCREASE_SHOPPING_COUNT = 'INCREASE_SHOPPING_COUNT'
const DECREASE_SHOPPING_COUNT = 'DECREASE_SHOPPING_COUNT'
const SET_DEFAULT_COMPANY = 'SET_DEFAULT_COMPANY'
const SAVE_COUNTRY_RATE = 'SAVE_COUNTRY_RATE'
const SAVE_SHOP_RATE = 'SAVE_SHOP_RATE'
const SET_COMPANY_BY_CID = 'SET_COMPANY_BY_CID'
const REMOVE_SHOPPING_BY_ID = 'REMOVE_SHOPPING_BY_ID'
const SET_FAQ = 'SET_FAQ'
const SET_FAQ_INDEX = 'SET_FAQ_INDEX'
const SET_FAQ_LOADED = 'SET_FAQ_LOADED'
const SET_COMPANY_AND_WAY = 'SET_COMPANY_AND_WAY'

/**
 * order module
 */
const SET_ORDER_LIST = 'SET_ORDER_LIST'
const SET_DISPLAY_ORDER = 'SET_DISPLAY_ORDER'
const CANCEL_ORDER = 'CANCEL_ORDER'
const SET_PACKAGE_LIST = 'SET_PACKAGE_LIST'
const SET_DISPLAY_PACKAGE = 'SET_DISPLAY_PACKAGE'
const SET_PACKAGE_IDS = 'SET_PACKAGE_IDS'
const SET_DEFAULT_PID = 'SET_DEFAULT_PID'
const SET_SHIP_WAY = 'SET_SHIP_WAY'
const SET_SHIP_BOX = 'SET_SHIP_BOX'
const ADD_SHIP_SERVICE = 'ADD_SHIP_SERVICE'
const DEL_SHIP_SERVICE = 'DEL_SHIP_SERVICE'
const CLEAR_SHIP_SERVICE = 'CLEAR_SHIP_SERVICE'
const SET_TRAN_ORDER_LIST = 'SET_TRAN_ORDER_LIST'
const SET_TRAN_ORDER_DETAIL = 'SET_TRAN_ORDER_DETAIL'
const RECEIPT_GOODS = 'RECEIPT_GOODS'
const SET_EXPRESS_DETAIL = 'SET_EXPRESS_DETAIL'
const SET_EXPRESS_SITE = 'SET_EXPRESS_SITE'

export {
  GEN_PAY,
  SET_LOADING,
  SET_SUBMIT_LOADING,
  SHOW_ALERT,
  SHOW_CONFIRM,
  HIDE_CONFIRM,
  SET_APP_CURRENCY,
  GET_CART_LIST,
  ADD_TO_CART,
  RECEIVE_SHOPPING_INFO,
  INIT_SHOPPING_DISPLAY,
  UPDATE_SHOPPING_DISPLAY,
  SELECT_ALL_SHOPPING,
  SELECT_SHOP_SHOPPING,
  SELECT_SHOPPING,
  INCREASE_SHOPPING_COUNT,
  DECREASE_SHOPPING_COUNT,
  SET_DEFAULT_COMPANY,
  SAVE_COUNTRY_RATE,
  SAVE_SHOP_RATE,
  SET_COMPANY_BY_CID,
  REMOVE_SHOPPING_BY_ID,
  SET_ORDER_LIST,
  SET_DISPLAY_ORDER,
  CANCEL_ORDER,
  SET_PACKAGE_LIST,
  SET_DISPLAY_PACKAGE,
  SET_DEFAULT_ADDRESS,
  SET_DEFAULT_PID,
  SET_PACKAGE_IDS,
  SET_SHIP_WAY,
  ADD_SHIP_SERVICE,
  DEL_SHIP_SERVICE,
  CLEAR_SHIP_SERVICE,
  SET_SHIP_BOX,
  SET_SELECT_ADDRESS,
  SET_MODIFY_ADDRESS,
  SET_TRAN_ORDER_LIST,
  SET_TRAN_ORDER_DETAIL,
  SET_PAY_ORDER,
  SET_FAQ,
  SET_FAQ_INDEX,
  SET_FAQ_LOADED,
  RECEIPT_GOODS,
  SET_COMPANY_AND_WAY,
  SET_EXPRESS_DETAIL,
  SET_EXPRESS_SITE
}
