const ADD_TO_CART = 'ADD_TO_CART'
const RECEIVE_SHOPPING_INFO = 'RECEIVE_SHOPPING_INFO'
const GET_CART_LIST = 'GET_CART_LIST'
const INIT_SHOPPING_DISPLAY = 'INIT_SHOPPING_DISPLAY'
const UPDATE_SHOPPING_DISPLAY = 'UPDATE_SHOPPING_DISPLAY'
const SELECT_ALL_SHOPPING = 'SELECT_ALL_SHOPPING'
const SELECT_SHOP_SHOPPING = 'SELECT_SHOP_SHOPPING'
const SELECT_SHOPPING = 'SELECT_SHOPPING'
const INCREASE_SHOPPING_COUNT = 'INCREASE_SHOPPING_COUNT'
const DECREASE_SHOPPING_COUNT = 'DECREASE_SHOPPING_COUNT'

export {
  GET_CART_LIST,
  ADD_TO_CART,
  RECEIVE_SHOPPING_INFO,
  INIT_SHOPPING_DISPLAY,
  UPDATE_SHOPPING_DISPLAY,
  SELECT_ALL_SHOPPING,
  SELECT_SHOP_SHOPPING,
  SELECT_SHOPPING,
  INCREASE_SHOPPING_COUNT,
  DECREASE_SHOPPING_COUNT
}
