const SWITCH_THREAD = 'SWITCH_THREAD'
const RECEIVE_SHOPPING_INFO = 'RECEIVE_SHOPPING_INFO'
const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'

export {
  SWITCH_THREAD,
  RECEIVE_SHOPPING_INFO,
  RECEIVE_MESSAGE
}
